### ISSUE TITLE
メール送信のアラートで、 キャンセルを押してもメールが送信されてしまう。

### ISSUE THREAD

**Issue by Naoto00** [cybozu/option#2]
https://github.com/cybozu/option/blob/master/kintone-mail-service_outlook/kintone-o365-connect.js#L537

上記の関数でキャンセルボタンを押下した際の処理が書いていないため、
キャンセルボタンを押下してもメールが送信されてしまう。

**Comment by shota-fujiwara** [comment]
We fixed it. Thank you.
